package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            text("env.DOCKER_HUB_USERNAME", "lantsovvova", readOnly = true, allowEmpty = false)
        }
        add {
            password("env.DOCKER_HUB_PASSWORD", "credentialsJSON:fccf4ddf-3779-4378-b9bb-66a8dc0b9fd7", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
    }
}
